/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A copilot instance driven by JSON commands. */
export declare class Copilot {
  /** Build a copilot from a spec JSON string. */
  constructor(specJson: string)
  /** Apply a command JSON and return the resulting response JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
